# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: server

steps:
- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
    connectedServiceName: 'dev109864-Parts Unlimited-ServiceNow DevOps Service Connection'
    changeRequestDetails: |
      {
          "setCloseCode" : true,
          "attributes": {
            "requested_by": {
              "name": "Naresh Gotad"
            },
            "start_date": "2023-09-13 08:00:00",
            "end_date": "2023-09-18 08:00:00",
            "std_change_producer_version": "2c4eeab447d57910bf14f7fb136d43da",
            "devops_change": "true",
          }
        }